name: 01 - Building Blocks
on:
  - push
  - workflow_dispatch
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"
  echo-goodbye:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          exit 1
          echo "I\n will\n fail\n"
      - name: Say goodbye
        run: echo "Goodbye!"
