name: 03 - Workflow Runners
on:
  push:
jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: echo $RUNNER_OS
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        shell: bash
        run: echo "${{ runner.os }}"
